# font
font_family   Iosevka
font_size 11.5

# cursor
cursor_shape block
cursor_beam_thickness 7
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_stop_blinking_after 15.0
scrollback_lines 10000

url_color #0c0c07
url_style straight
detect_urls yes
open_url_with default

pointer_shape_when_grabbed arrow
enable_audio_bell no

active_border_color #0c2c0c

background_blur 32
background_opacity 0.97
shell_integration enabled

editor nvim
clipboard_max_size 10000
include rose-pine.conf 
# include mfd-mono.conf
