# make sure to clone the tpm-redux repo before setting things up.
# List of plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-logging'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'clanghans/tmux-frost'

# set a better limit
set -g history-limit 50000

# remap prefix from 'C-b' to 'C-a'
set -g prefix C-a	
set-option -g default-command $SHELL

# Mouse!??
set-option -g mouse on

# Custom remaps:
bind-key K kill-session

# switch panes using Alt-arrow without prefix
bind -n M-h        select-pane -L
bind -n M-l        select-pane -R
bind -n M-k        select-pane -U
bind -n M-j        select-pane -D

# Switch sessions effortlessly:
bind-key -n 'M-]' switch-client -n
bind-key -n 'M-[' switch-client -p

# effortlessly reload config (might be useless as a result of HM)
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# General
setw -g mode-keys vi
set-option -g allow-rename off
set -g base-index 1
set -g pane-active-border-style fg="blue"

# status customization:
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""
set -g renumber-windows on
set -g status-left-length 76 # could be any number :)

# Base16 Black Metal
# Scheme author: metalelf0 (https://github.com/metalelf0)
# Template author: Tinted Theming: (https://github.com/tinted-theming)

# default statusbar colors
set-option -g status-style "fg=#999999,bg=#121212"

# default window title colors
set-window-option -g window-status-style "fg=#999999,bg=#121212"

# active window title colors
set-window-option -g window-status-current-style "fg=#a06666,bg=#121212"

# pane border
set-option -g pane-border-style "fg=#121212"
set-option -g pane-active-border-style "fg=#999999"

# message text
set-option -g message-style "fg=#999999,bg=#222222"

# pane number display
set-option -g display-panes-active-colour "#999999"
set-option -g display-panes-colour "#121212"

# copy mode highlight
set-window-option -g mode-style "fg=#999999,bg=#222222"

# bell
set-window-option -g window-status-bell-style "fg=#000000,bg=#5f8787"

# style for window titles with activity
set-window-option -g window-status-activity-style "fg=#c1c1c1,bg=#121212"

# style for command messages
set-option -g message-command-style "fg=#999999,bg=#222222"

# options for tmux-frost:
set -g @frost-auto-restore 'on' # auto-restore
set -g @frost-auto-save-interval '20' # auto-save every N minutes
set -g @frost-dir '~/.local/share/tmux/frost'
set -g @frost-delete-backup-after '30'


# Initialize TPM Redux
run '~/.tmux/plugins/tpm-redux/tpm'
